name: tfm-bandas
networks: { tfm_net: {} }
volumes:  { mysql_data: {}, keycloak_data: {} }

services:

  keycloak:
    build: 
      context: ./config/keycloak/
      dockerfile: Dockerfile
    env_file:
      - env/local.env
    command: ["start-dev","--import-realm"]
    volumes:
      - ./config/keycloak/realm-tfm-bandas.json:/opt/keycloak/data/import/realm-tfm-bandas.json:ro
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass
      KC_REALM: ${KC_REALM}
    ports: ["${KEYCLOAK_PORT}:8080"]
    depends_on:
      keycloak-mysql: { condition: service_healthy }
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/realms/$${KC_REALM:-tfm-bandas}/protocol/openid-connect/certs || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s
    # profiles: ["keycloak"]
    networks: [tfm_net]

  keycloak-mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakpass
      MYSQL_ROOT_PASSWORD: rootpass
    env_file:
      - env/local.env
    volumes:
      - keycloak_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    ports: ["${KEYCLOAK_MYSQL_PORT}:3306"]   # expone en 3308 para que no choque con tu otro MySQL
    # profiles: ["db","keycloak"]
    networks: [tfm_net]

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tfm_users 
    ports: ["${MYSQL_PORT}:3306"]
    env_file:
      - env/local.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    # profiles: ["db","users","events"]
    networks: [tfm_net]

  users:
    build:
      context: ${USUARIOS_DIR}
      dockerfile: Dockerfile
    env_file:
      - env/local.env
    depends_on:
      mysql:    { condition: service_healthy }
      keycloak: { condition: service_started }
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${USERS_DB}
      DB_USER: ${USERS_USER}
      DB_PASS: ${USERS_PASS}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: ${KC_JWKS}
      IDENTITY_SERVICE_URI: ${IDENTITY_SERVICE_URI}
    ports: ["${USERS_PORT}:8080"]
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    # profiles: ["users"]
    networks: [tfm_net]

  events:
    build:
      context: ${EVENTS_DIR}
      dockerfile: Dockerfile
    env_file:
      - env/local.env
    depends_on:
      mysql:    { condition: service_healthy }
      keycloak: { condition: service_started }
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${EVENTS_DB}
      DB_USER: ${EVENTS_USER}
      DB_PASS: ${EVENTS_PASS}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: ${KC_JWKS}
      EVENTS_RULES_MIN_DURATION_MINUTES: 15
      EVENTS_RULES_MAX_DURATION_HOURS: 240
      EVENTS_RULES_ALLOW_OVERLAP_SAME_LOCATION: "true"
      EVENTS_RULES_ALLOW_CREATE_IN_PAST: "true"
    ports: ["${EVENTS_PORT}:8080"]
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    # profiles: ["events"]
    networks: [tfm_net]

  surveys:
    build:
      context: ${SURVEYS_DIR}
      dockerfile: Dockerfile
    env_file:
      - env/local.env
    depends_on:
      mysql:    { condition: service_healthy }
      keycloak: { condition: service_started }
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${SURVEYS_DB}
      DB_USER: ${SURVEYS_USER}
      DB_PASS: ${SURVEYS_PASS}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: ${KC_JWKS}
      EVENTS_SERVICE_URI: ${GATEWAY_EVENTS_URI}
      EVENTS_SERVICE_EXISTS_PATH: /api/events/{eventId}
    ports: ["${SURVEYS_PORT}:8080"]
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks: [tfm_net]

  identity:
    build:
      context: ${IDENTITY_DIR}
      dockerfile: Dockerfile
    env_file:
      - env/local.env
    depends_on:
      keycloak: { condition: service_started }
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: ${KC_JWKS}
      KEYCLOAK_AUTH_URL: ${KC_URL_INTERNAL}
      KEYCLOAK_REALM: ${KC_REALM}
      KEYCLOAK_ADMIN_CLIENT_ID: ${KC_ADMIN_CLIENT_ID}
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KC_ADMIN_CLIENT_SECRET}
      KEYCLOAK_PERMITTED_ROLES: ${KC_PERMITTED_ROLES}
    ports:
      - "${IDENTITY_PORT}:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    # profiles: ["identity"]
    networks: [tfm_net]



  gateway:
    build:
      context: ${GATEWAY_DIR}
      dockerfile: Dockerfile
    env_file:
      - env/local.env
    depends_on:
      keycloak: { condition: service_started }
      users: { condition: service_healthy }
      events:  { condition: service_healthy }
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: ${KC_JWKS}
      GATEWAY_USERS_URI: ${GATEWAY_USERS_URI}
      GATEWAY_EVENTS_URI: ${GATEWAY_EVENTS_URI}
      GATEWAY_SCORES_URI: ${GATEWAY_SCORES_URI}
      GATEWAY_SURVEYS_URI: ${GATEWAY_SURVEYS_URI}
      GATEWAY_USERS_PATH: ${GATEWAY_USERS_PATH}
      GATEWAY_INSTRUMENTS_PATH: ${GATEWAY_INSTRUMENTS_PATH}
      GATEWAY_ROLES_PATH: ${GATEWAY_ROLES_PATH}
      GATEWAY_EVENTS_PATH: ${GATEWAY_EVENTS_PATH}
      GATEWAY_SCORES_PATH: ${GATEWAY_SCORES_PATH}
      GATEWAY_SURVEYS_PATH: ${GATEWAY_SURVEYS_PATH}
    ports: ["${GATEWAY_PORT}:8080"]
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    # profiles: ["gateway"]
    networks: [tfm_net]


# Ejemplos de uso:
# Arrancar todos los servicios: 
#     docker compose --env-file env/local.env --profile keycloak --profile db --profile users --profile events --profile gateway up -d --build

# Arrancar solo Keycloak
#     docker compose --env-file env/local.env --profile keycloak up -d

# Arrancar solo la base de datos MySQL
#     docker compose --env-file env/local.env --profile db up -d

# Arrancar solo Usuarios y sus dependencias (Keycloak + DB):
#     docker compose --env-file env/local.env --profile keycloak --profile db --profile users up -d
#   Si mysql y keycloak ya están arriba:
#     docker compose --profile users up -d

# Arrancar solo Eventos y sus dependencias (Keycloak + DB):
#     docker compose --env-file env/local.env --profile keycloak --profile db --profile events up -d
#   Si mysql y keycloak ya están arriba: 
#     docker compose --env-file env/local.env --profile events up -d

# Cuando se hace un cambio en ../usuarios o ../eventos:
# 1) mvn -DskipTests package
# 2) docker compose --env-file env/local.env restart <service>

# Parar/bajar todo:
#     docker compose --env-file env/local.env stop -> para pero no borra
#     docker compose --env-file env/local.env down -> para y borra
#     docker compose --env-file env/local.env down -volumes -> para, borra y elimina volúmenes (datos)

# Logs:
# docker compose --env-file env/local.env logs -f <service>


# Verificar JWKS (JSON Web Key Set) en Keycloak desde el contenedor de usuarios o eventos:
# docker compose exec usuarios curl -X GET http://keycloak:8080/realms/tfm-bandas/protocol/openid-connect/certs
# docker compose exec events curl -X GET http://keycloak:8080/realms/tfm-bandas/protocol/openid-connect/certs
# o
# docker compose exec usuarios sh -lc "wget -q -O- http://keycloak:8080/realms/tfm-bandas/protocol/openid-connect/certs | head"
# docker compose exec events sh -lc "wget -q -O- http://keycloak:8080/realms/tfm-bandas/protocol/openid-connect/certs | head"
